# Generated by Django 2.2.12 on 2022-06-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plovilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proizvodac', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('godina_proizvodnje', models.IntegerField()),
                ('iznajmljen', models.BooleanField(default=False)),
                ('korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Korisnik')),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='plaza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Plaza'),
        ),
    ]
